version: "3.9"
services:
  db:
    image: postgres:15
    container_name: emd_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql:ro

  api:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.api
    container_name: emd_api
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./db:/app/db
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  etl:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.etl
    container_name: emd_etl
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./etl:/app/etl
      - ./db:/app/db
    command: python -m etl.scheduler

  dashboard:
    build:
      context: ./dashboard
      dockerfile: ../infra/Dockerfile.dashboard
    container_name: emd_dashboard
    env_file: .env
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./dashboard:/usr/src/app
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  db_data: